[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
wallets = "AVMA24bYvmoq1CiaGM8v8wdhzj2K5u5vFzstS9pHztLv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/niels/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
